package uu.mgag.util.enums;

public enum EnumEntityStage {
	NONE, 
	IDLE, 
	MOVE_TO_SUPPLY_POINT_FOOD,
	MOVE_TO_SUPPLY_POINT_BUILD,
	MOVE_TO_SUPPLY_POINT_OTHER,
	MOVE_TO_SUPPLY_POINT_ORES,
	MOVE_TO_BUILD_SITE,
	DECIDE_NEXT_BUILD,
	BUILD,
	SPAWN,
	DEPOSIT_RESOURCES, 
	GATHER_RESOURCES,
	CONVERT_RESOURCES,
	POST_GATHER_RESOURCES, 
	MOVE_TO_WORKING_REFERENCE_POINT,
	RETURN_HOME,
	TAKE_TOOLS;
}
